# Generated by Django 2.2.25 on 2022-12-24 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planID",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("planName", models.CharField(max_length=149)),
                (
                    "amountOptions",
                    models.CharField(
                        choices=[("cash", "cash"), ("bitcoin", "bitcoin")],
                        default="cash",
                        max_length=15,
                    ),
                ),
                (
                    "tenureOptions",
                    models.IntegerField(
                        choices=[(1, 1), (3, 3), (6, 6), (9, 9)], default=1
                    ),
                ),
                ("benefitPercentage", models.FloatField(default=0)),
                (
                    "benefitType",
                    models.CharField(
                        choices=[
                            ("cashback", "cashback"),
                            ("extraovucher", "extravoucher"),
                        ],
                        default="cashback",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotionID",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=149)),
                ("max_users", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("benefitPercentage", models.FloatField(default=0)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="tortoise.Plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerGoals",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.CharField(max_length=30)),
                ("selectedAmount", models.IntegerField()),
                ("selectedTenure", models.IntegerField(default=1)),
                ("startedDate", models.DateField(auto_now_add=True)),
                ("depositedAmount", models.IntegerField()),
                ("benefitPercentage", models.FloatField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tortoise.Plan",
                    ),
                ),
            ],
        ),
    ]
